name: Build and Publish Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.DOCKER_REGISTRY || 'ghcr.io' }}
  IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME || github.repository }}
  PRIVATE_REGISTRY_URL: ${{ vars.PRIVATE_REGISTRY_URL }}
  PRIVATE_REGISTRY_USER: ${{ secrets.PRIVATE_REGISTRY_USER }}
  PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

jobs:
  build-and-push:
    # You can specify GitHub-hosted runners
    # runs-on: ubuntu-latest
    # runs-on: ubuntu-22.04
    # runs-on: windows-2022
    # runs-on: macos-12
    runs-on: ubuntu-latest
    
    # Or use self-hosted runners with labels
    # runs-on: [linux, x64]
    
    # You can also use multiple labels to target specific runners
    # runs-on: [self-hosted, linux, x64, production]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to the GitHub Container registry
        if: ${{ !env.PRIVATE_REGISTRY_URL }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Log in to private registry if configured
      - name: Log in to private registry
        if: ${{ env.PRIVATE_REGISTRY_URL != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PRIVATE_REGISTRY_URL }}
          username: ${{ env.PRIVATE_REGISTRY_USER }}
          password: ${{ env.PRIVATE_REGISTRY_PASSWORD }}

      # Extract metadata for GitHub Container Registry
      - name: Extract metadata for GitHub Container Registry
        id: meta-ghcr
        if: ${{ !env.PRIVATE_REGISTRY_URL }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
            
      # Extract metadata for private registry
      - name: Extract metadata for private registry
        id: meta-private
        if: ${{ env.PRIVATE_REGISTRY_URL != '' }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PRIVATE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short

      # Build and push to GitHub Container Registry
      - name: Build and push Docker image to GitHub Container Registry
        if: ${{ !env.PRIVATE_REGISTRY_URL }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-ghcr.outputs.tags }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # Build and push to private registry
      - name: Build and push Docker image to private registry
        if: ${{ env.PRIVATE_REGISTRY_URL != '' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-private.outputs.tags }}
          labels: ${{ steps.meta-private.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
